### ISSUE TITLE
Builder is breaking once it reaches templates/telegram-desktop/ themes

### ISSUE THREAD

**Issue by jonleopard** [belak/base16-builder-go#10]
Hello,

There is an issue once the builder reaches telegram-desktop themes:

```
INFO[0002] Rendering template default in templates/telegram-desktop 
FATA[0002] open templates/telegram-desktop/themes/base16-atelier-savanna: is a directory
```

This same error is actually happening in another project (base16-vim-lightline), I've opened up an [issue](https://github.com/mike-hearn/base16-vim-lightline/issues/1) there as well. I'm pretty new to Go, but is there a way the builder can handle directories?

**Comment by belak** [comment]
Oh boy... I'm not actually sure what to do with this - they use a custom build.sh script which only works with the python base16-builder.

**Comment by belak** [comment]
Well, I've added --ignore-errors to the build subcommand (in 330e471). You can also provide the name of the template you want to build.

However, this is just a stop-gap. I'm not sure how projects like this which break builders should be handled by the upstream base16 project since one of the ideas is that you should be able to fire up any builder and build everything..

**Comment by belak** [comment]
I've also opened https://github.com/chriskempson/base16-templates-source/issues/62 and revived https://github.com/chriskempson/base16/issues/52 to (hopefully) start a discussion around what to do with repos like this which don't conform to the base16 spec but are still built with base16

**Comment by jonleopard** [comment]
Chris seems to be pretty absent these days, but I'm also hopeful we can find a way to resolve this and (perhaps) prevent it from happening again in the future. 

Thanks for providing all the info as well as creating this tool :)

**Comment by belak** [comment]
This has been fixed as of the latest release - we don't attempt to build all templates now.
