### ISSUE TITLE
Go build failed because of the repo names "github.com/sirupsen/logrus"

### ISSUE THREAD

**Issue by Jaxx4Fun** [belak/base16-builder-go#11]
I just clone the repo and tried 
`go build ./main.go` 
here is what I go
> go: github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod:
	module declares its path as: github.com/sirupsen/logrus
	        but was required as: github.com/Sirupsen/logrus

So I think the lower-cased url of repo is the one.
BTW: I am using goproxy which might be the difference?

**Comment by belak** [comment]
This should be resolved now. Thanks for reporting!
