### ISSUE TITLE
Failed to update schemes: The Remote does not match the VCS endpoint    source=nord

### ISSUE THREAD

**Issue by choucavalier** [belak/base16-builder-go#13]
With the last `master` version, when trying to update schemes, I get the following output
```
λ ./base16-builder-go update
INFO[0000] Updating sources                             
INFO[0001] Updating schemes                             
ERRO[0060] The Remote does not match the VCS endpoint    source=nord
FATA[0060] Failed to update schemes
```
Any idea of what could be happening?

**Comment by belak** [comment]
This has changed as-of the latest release and shouldn't be relevant any more. What was happening is that we changed the location of the nord scheme file in the upstream sources repo, and this builder didn't handle that edge case.
