### ISSUE TITLE
Distribute prebuilt binaries

### ISSUE THREAD

**Issue by averms** [belak/base16-builder-go#14]
As it stands, this seems to be one of the most complete base16 builders. It would be nice to have it available as a quick download.

**Comment by belak** [comment]
That sounds like a great idea! I don't know if I'll have time to do this any time soon but I'd be happy to accept a PR doing this, possibly through Github actions.

**Comment by belak** [comment]
Currently they're manually built, but I've added binaries built with goreleaser to the releases page!
