### ISSUE TITLE
How can I add my theme?

### ISSUE THREAD

**Issue by Mauladen** [belak/base16-builder-go#7]
Good afternoon, I liked your builder that it is written in Goland and it's great.
I would be very happy if you could tell me how to add your topic and collect all based on it.
The documentation simply says that it clones the repository and then builds it.

**Comment by belak** [comment]
The base16 builder spec is maintained at https://github.com/chriskempson/base16/blob/master/builder.md and the list of scheme repositories is kept at https://github.com/chriskempson/base16-schemes-source.

This repository is based on this spec and uses it to clone all the schemes and templates and build them into actual schemes.

**Comment by Mauladen** [comment]
Can you tell me how to start a builder?

**Comment by belak** [comment]
Are you looking to write your own builder or just run this one?

**Comment by Mauladen** [comment]
I want to run

**Comment by belak** [comment]
There are a few steps to running it. The easiest method would be to use `go get github.com/belak/base16-builder-go` to build and install a binary. Once that's done, you can run `base16-builder-go update` and `base16-builder-go build`.

**Comment by Mauladen** [comment]
it will be cool if you would add the manual for build in the README

**Comment by belak** [comment]
It sounds like this was resolved a while back so I'm going to close this. If you feel the README documentation could use an update, I'd welcome a PR. Cheers!
